"""initial schema matching current models

Revision ID: 108348c6e227
Revises: None
Create Date: 2026-08-22 12:20:09.428442

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '108348c6e227'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('capabilities',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employees',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('services',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('capability_scores',
    sa.Column('employee_id', sa.String(length=50), nullable=False),
    sa.Column('capability_id', sa.String(length=50), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('evidence_count', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['capability_id'], ['capabilities.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('employee_id', 'capability_id')
    )
    op.create_table('modules',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('service_id', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidence_records',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('employee_id', sa.String(length=50), nullable=False),
    sa.Column('capability_id', sa.String(length=50), nullable=False),
    sa.Column('module_id', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('source_ref', sa.String(length=100), nullable=False),
    sa.Column('event_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['capability_id'], ['capabilities.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('module_capabilities',
    sa.Column('module_id', sa.String(length=50), nullable=False),
    sa.Column('capability_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['capability_id'], ['capabilities.id'], ),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ),
    sa.PrimaryKeyConstraint('module_id', 'capability_id')
    )
    op.execute("DROP TABLE IF EXISTS employee_capabilities CASCADE")
    op.execute("DROP TABLE IF EXISTS component_dependencies CASCADE")
    op.execute("DROP TABLE IF EXISTS organizations CASCADE")
    op.execute("DROP TABLE IF EXISTS system_dependencies CASCADE")
    op.execute("DROP TABLE IF EXISTS projects CASCADE")
    op.execute("DROP TABLE IF EXISTS components CASCADE")
    op.execute("DROP TABLE IF EXISTS systems CASCADE")
    op.execute("DROP TABLE IF EXISTS evidence CASCADE")
    op.execute("DROP TABLE IF EXISTS teams CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('raw_jira_issues_jira_id_key'), 'raw_jira_issues', ['jira_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('raw_incidents_incident_id_key'), 'raw_incidents', ['incident_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('raw_github_reviews_review_id_key'), 'raw_github_reviews', ['review_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('raw_github_pull_requests_pr_id_key'), 'raw_github_pull_requests', ['pr_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('raw_github_issues_issue_id_key'), 'raw_github_issues', ['issue_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('raw_github_commits_commit_id_key'), 'raw_github_commits', ['commit_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('raw_documents_doc_id_key'), 'raw_documents', ['doc_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('raw_deployments_deployment_id_key'), 'raw_deployments', ['deployment_id'], postgresql_nulls_not_distinct=False)
    op.create_table('teams',
    sa.Column('team_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('fk_team_project')),
    sa.PrimaryKeyConstraint('team_id', name=op.f('teams_pkey'))
    )
    op.create_table('evidence',
    sa.Column('evidence_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('capability_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('evidence_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('strength', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('observed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('source_reference', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.CheckConstraint('strength >= 0::numeric AND strength <= 1::numeric', name=op.f('chk_evidence_strength_value')),
    sa.PrimaryKeyConstraint('evidence_id', name=op.f('evidence_pkey'))
    )
    op.create_table('systems',
    sa.Column('system_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('criticality', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('fk_system_project')),
    sa.PrimaryKeyConstraint('system_id', name=op.f('systems_pkey'))
    )
    op.create_table('components',
    sa.Column('component_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('system_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('component_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('criticality', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['system_id'], ['systems.system_id'], name=op.f('fk_component_system')),
    sa.PrimaryKeyConstraint('component_id', name=op.f('components_pkey'))
    )
    op.create_table('projects',
    sa.Column('project_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.organization_id'], name=op.f('fk_project_organization')),
    sa.PrimaryKeyConstraint('project_id', name=op.f('projects_pkey'))
    )
    op.create_table('system_dependencies',
    sa.Column('dependency_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('source_system_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('target_system_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('dependency_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('weight', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.CheckConstraint('weight >= 0::numeric AND weight <= 1::numeric', name=op.f('chk_system_weight')),
    sa.ForeignKeyConstraint(['source_system_id'], ['systems.system_id'], name=op.f('fk_source_system')),
    sa.ForeignKeyConstraint(['target_system_id'], ['systems.system_id'], name=op.f('fk_target_system')),
    sa.PrimaryKeyConstraint('dependency_id', name=op.f('system_dependencies_pkey'))
    )
    op.create_table('organizations',
    sa.Column('organization_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('industry', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('organization_id', name=op.f('organizations_pkey'))
    )
    op.create_table('component_dependencies',
    sa.Column('dependency_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('source_component_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('target_component_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('dependency_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('weight', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.CheckConstraint('weight >= 0::numeric AND weight <= 1::numeric', name=op.f('chk_component_weight')),
    sa.ForeignKeyConstraint(['source_component_id'], ['components.component_id'], name=op.f('fk_source_component')),
    sa.ForeignKeyConstraint(['target_component_id'], ['components.component_id'], name=op.f('fk_target_component')),
    sa.PrimaryKeyConstraint('dependency_id', name=op.f('component_dependencies_pkey'))
    )
    op.create_table('employee_capabilities',
    sa.Column('employee_capability_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('capability_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('evidence_strength', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('evidence_recency', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('confidence', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.CheckConstraint('confidence >= 0::numeric AND confidence <= 1::numeric', name=op.f('chk_confidence')),
    sa.CheckConstraint('evidence_recency >= 0::numeric AND evidence_recency <= 1::numeric', name=op.f('chk_evidence_recency')),
    sa.CheckConstraint('evidence_strength >= 0::numeric AND evidence_strength <= 1::numeric', name=op.f('chk_evidence_strength')),
    sa.PrimaryKeyConstraint('employee_capability_id', name=op.f('employee_capabilities_pkey')),
    sa.UniqueConstraint('employee_id', 'capability_id', name=op.f('employee_capabilities_employee_id_capability_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('module_capabilities')
    op.drop_table('evidence_records')
    op.drop_table('modules')
    op.drop_table('capability_scores')
    op.drop_table('services')
    op.drop_table('employees')
    op.drop_table('capabilities')
    # ### end Alembic commands ###
